### ISSUE TITLE
Proposal: do not establish session in identity handshake

### ISSUE THREAD

**Issue by drbild** [xaptum/xtt-spec#1]
The intended lifetime flow for a device looks something like this:

              [First Boot]
                    |
                    v
           [Identity Handshake]
                    | + and *
                    v
    [Reboot] <--- [Run] ---> [Session Handshake ]
         |         ^ ^               | *
         |         | |               |
         ----------  -----------------
    
    + Provision identity
    * Establish session keys

In the current protocol, session keys are establish during both handshakes. To reduce duplication and simplify the protocol, I propose removing the session key establishment from the identity handshake. Clients will instead need to run both the identity and session handshakes on first boot.

The identity handshake is intended to be run just once in a device lifetime --- one additional handshake is not a significant cost.

Separating these has three big advantages:

- the purposes of the handshakes is made more clear.  The first does only identity provisioning and the second does only session establishment.

- the protocol is simplified and duplication is removed. The logic for session key establishment will exist only in the session handshake.

- the flow is simplified, reducing the chances for implementation errors.

**Comment by zanebeckwith** [comment]
The main reason I had for provisioning session keys during the identity handshake was for the users who want full unlinkability: run an identity handshake with random-base DAA for _each_ session (or even each message). 

I don't know how interesting such a use case would be for anyone, though. For Industry 4.0, anonymity and unlinkability are probably of zero interest. But for situations where personal data is being moved, they might be much more interesting.

**Comment by drbild** [comment]
That's right - jogging my memory. (I'm working through the protocol description, looking for parts I wish were simpler.)

Given the IoT landscape today, I expect that per-message unlinkability wouldn't be used for many years.  Nothing precludes a future version of the protocol from supporting keys/data in the provisioning handshake. Thus, I'm leaning towards removing it.  Keep the protocol as simple as possible for the 80% use-case today, but compatible with future backward-compatible support for these features.

I think it's important that support was designed in, to ensure that future support is possible. And in fact, given that we have the design, we should document in an appendix what the future protocol extension would look like.  But in the interest of reducing complexity, it would be good to remove the "we're not sure anyone wants this" features for now.

Thoughts?

**Comment by zanebeckwith** [comment]
After going over multiple ways of altering the protocol to make it clearer while still allowing session and id provisioning, I think I'm on your side.

I would really prefer to not push off fundamental questions (when is this secret material created?) to future versions, just because version negotiation in TLS is so nasty.

But, I agree that it's confusing, and all the variants I could come up with still have too many "if this, then...".

So, it's frustrating, because I feel like a clean, straight-forward version of the protocol is so close, but I'll make the two handshakes completely separate. Agreed that there's no point in making the common case complex for the sake of a possible future case.
